# ShiroFilterFactoryBean对象配置
loginUrl: "/unauth"
successUrl: "/index"
unauthorizedUrl: "/403"

# 注意过滤器配置顺序 不能颠倒
# 配置退出 过滤器,其中的具体的退出代码Shiro已经替我们实现了，登出后跳转配置的loginUrl
filterChainDefinitionMap:
    /logout: "logout"
    /sysUser/**: "anon"
#    /sysUserRole/**: "anon"
#    /sysRoleResource/**: "anon"
#    /sysRole/**: "anon"
#    /sysResource/**: "anon"
    /static/**: "anon"
    /ajaxLogin: "anon"
    /login: "anon"
    /**: "authc"
