# 注意过滤器配置顺序 不能颠倒
# 配置退出 过滤器,其中的具体的退出代码Shiro已经替我们实现了，登出后跳转配置的loginUrl
#ec: 
#  logout: "logout"
#  filter:
#    /logout: "logout"
#    /static/**: "anon"
#    /ajaxLogin: "anon"
#    /login: "anon"
#    /**: "authc"
#    
    
filter:
    /logout: "logout"
    /static/**: "anon"
    /ajaxLogin: "anon"
    /login: "anon"
    /**: "authc"